### ISSUE TITLE
build package with full file extension

### ISSUE THREAD

**Issue by shrilakshmishastry** [ad1992/fuzzify#15]
Hey @ad1992 👋 
Good work on fuzzi logic 👏  

I am facing the below issue, can you please look into it or assign me?

Issue: 
Unable to resolve file or component due to missing file extension in the import statement. This is happening because the target of tsc is `esNext`, whereas the consuming package that uses webpack targets `es5`

**Not able to resolve utils**
<img width="677" alt="Screenshot 2024-08-03 at 4 51 13 PM" src="https://github.com/user-attachments/assets/d34f5dcd-6597-4384-8b08-ba37e7ec7937">

**Not able to get fuzzzy**
<img width="1335" alt="Screenshot 2024-08-03 at 4 51 29 PM" src="https://github.com/user-attachments/assets/ae71ae9f-164c-4d8e-b7df-8830a64cd280">

Solution:

When the package is consumed in other packages, since the bundler will use the bundled package, it doesn't resolve the extension. 
The fuzzify package needs to configure the tsc to compile to all browser or consuming package supporting a common version i.e `es5`

**Comment by ad1992** [comment]
@shrilakshmishastry this is issue specific to webpack and since the dev mode still uses webpack hence the above error, I have pushed the fix in `react-tags` repo in https://github.com/react-tags/react-tags/pull/986  and now it should work. Also for the integration please use the version [`0.1.2-test3`](https://www.npmjs.com/package/fuzzify/v/0.2.0-test3), I have pushed the  type fixes to the library so type imports would work fine too.
